Update to 5.4

diff --git a/UnrealEngine/Engine/Extras/Containers/Dockerfiles/linux/dev/Dockerfile b/UnrealEngine/Engine/Extras/Containers/Dockerfiles/linux/dev/Dockerfile
--- a/UnrealEngine/Engine/Extras/Containers/Dockerfiles/linux/dev/Dockerfile
+++ b/UnrealEngine/Engine/Extras/Containers/Dockerfiles/linux/dev/Dockerfile
@@ -1,12 +1,14 @@
-# This file was generated by ue4-docker version 0.0.102 with the following options:
+# This file was generated by ue4-docker version 0.0.112 with the following options:
 # 
-# - buildgraph_args: "-set:WithLinuxArm64=false -set:WithClient=true -set:WithServer=true"
+# - buildgraph_args: "-set:BuildIdOverride=UE_5.4 -set:WithLinuxArm64=false -set:WithClient=true -set:WithServer=true"
 # - combine: true
 # - credential_mode: "secrets"
 # - disable_all_patches: true
 # - disable_labels: true
-# - enable_dso_patch: true
+# - enable_dso_patch: false
+# - enable_ushell: true
 # - excluded_components: {"ddc": false, "debug": false, "templates": false}
+# - gitdependencies_args: ""
 # 
 # This Dockerfile combines the steps for the following images:
 # 
@@ -39,6 +41,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 		curl \
 		git \
 		git-lfs \
+		gpg-agent \
 		python3 \
 		python3-dev \
 		python3-pip \
@@ -48,6 +51,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 		tzdata \
 		unzip \
 		xdg-user-dirs \
+		xdg-utils \
 		zip && \
 	rm -rf /var/lib/apt/lists/* && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
@@ -60,6 +64,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 			libcairo2 \
 			libfontconfig1 \
 			libfreetype6 \
+			libgbm1 \
 			libglu1 \
 			libnss3 \
 			libnspr4 \
@@ -82,15 +87,6 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 			xkb-data && \
 	rm -rf /var/lib/apt/lists/* && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
-# Install the glibc DSO patch to improve Editor startup times
-RUN add-apt-repository -y ppa:slonopotamus/glibc-dso && \
-	apt-get update && \
-	apt upgrade -y libc6 && \
-	rm -rf /var/lib/apt/lists/* && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
-
-# Enable the glibc DSO patch
-ENV GLIBC_TUNABLES=glibc.rtld.dynamic_sort=2
-
 # Disable the default "lecture" message the first time a user runs a command using sudo
 RUN echo 'Defaults lecture="never"' >> /etc/sudoers && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
@@ -99,6 +95,17 @@ RUN useradd --create-home --home /home/ue4 --shell /bin/bash --uid 1000 ue4 && \
 	passwd -d ue4 && \
 	usermod -a -G audio,video,sudo ue4 && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 USER ue4
+
+# Install Python 3.12, which is required by ushell
+USER root
+RUN add-apt-repository -y ppa:deadsnakes/ppa && \
+	apt-get update && \
+	apt-get install -y --no-install-recommends python3.12 python3.12-venv && \
+	rm -rf /var/lib/apt/lists/* && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
+USER ue4
+
+# Install a copy of pip for Python 3.12
+RUN curl -fsSL 'https://bootstrap.pypa.io/get-pip.py' | python3.12 && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
 # Enable Git Large File Storage (LFS) support
 RUN git lfs install && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
@@ -140,11 +147,7 @@ RUN mkdir "$UE_GITDEPS" && echo '' && echo 'RUN directive complete. Docker will 
 # When running with BuildKit, we use a cache mount to cache the dependency data across multiple build invocations
 WORKDIR /home/ue4/UnrealEngine
 RUN --mount=type=cache,target=/home/ue4/gitdeps,uid=1000,gid=1000 sudo apt-get update && \
-	./Setup.sh \
-		--exclude=Android \
-		--exclude=Mac \
-		--exclude=Win32 \
-		--exclude=Win64 && \
+	./Setup.sh  && \
 	sudo rm -rf /var/lib/apt/lists/* && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
 FROM source as builder
@@ -160,21 +163,35 @@ RUN rm -rf /home/ue4/UnrealEngine/.git && echo '' && echo 'RUN directive complet
 # Ensure UBT is built before we create the Installed Build, since Build.sh explicitly sets the
 # target .NET Framework version, whereas InstalledEngineBuild.xml just uses the system default,
 # which can result in errors when running the built UBT due to the wrong version being targeted
-RUN ./Engine/Build/BatchFiles/Linux/Build.sh UnrealHeaderTool Linux Development -SkipBuild -buildubt && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
+RUN ./Engine/Build/BatchFiles/Linux/Build.sh ShaderCompileWorker Linux Development -SkipBuild -buildubt && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
 # Create an Installed Build of the Engine
 WORKDIR /home/ue4/UnrealEngine
 RUN ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph \
-    -target="Make Installed Build Linux" \
-    -script=Engine/Build/InstalledEngineBuild.xml \
-    -set:HostPlatformOnly=true \
-    -set:WithDDC=true \
-    -set:WithLinuxArm64=false -set:WithClient=true -set:WithServer=true && \
+	-target="Make Installed Build Linux" \
+	-script=Engine/Build/InstalledEngineBuild.xml \
+	-set:HostPlatformOnly=true \
+	-set:WithDDC=true \
+	-set:BuildIdOverride=UE_5.4 -set:WithLinuxArm64=false -set:WithClient=true -set:WithServer=true && \
 	rm -R -f /home/ue4/UnrealEngine/LocalBuilds/InstalledDDC && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
 # Split out components (DDC, debug symbols, template projects) so they can be copied into the final container image as separate filesystem layers
 COPY split-components.py /tmp/split-components.py
 RUN python3 /tmp/split-components.py /home/ue4/UnrealEngine/LocalBuilds/Engine/Linux /home/ue4/UnrealEngine/Components && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
+
+# Ensure UnrealVersionSelector is built, since the prebuilt binaries may not be up-to-date
+RUN ./Engine/Build/BatchFiles/Linux/Build.sh UnrealVersionSelector Linux Shipping && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
+
+# Copy InstalledBuild.txt from the Installed Build and run UnrealVersionSelector to populate Install.ini with any custom Build ID specified in the BuildGraph flags
+# (Note that the `-unattended` flag used below requires Unreal Engine 4.22 or newer, so this will break under older versions)
+# (Note also that custom Build IDs are supported by Unreal Engine 5.3.1 and newer, and older versions will just use a GUID as the Build ID)
+RUN cp /home/ue4/UnrealEngine/LocalBuilds/Engine/Linux/Engine/Build/InstalledBuild.txt /home/ue4/UnrealEngine/Engine/Build/InstalledBuild.txt && \
+	./Engine/Binaries/Linux/UnrealVersionSelector-Linux-Shipping -register -unattended && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
+
+# Ensure ushell is copied to the Installed Build
+RUN rm -rf ./LocalBuilds/Engine/Linux/Engine/Extras/ushell && \
+	cp -r ./Engine/Extras/ushell ./LocalBuilds/Engine/Linux/Engine/Extras/ushell && \
+	bash -c 'set -e; shopt -s globstar; cd /home/ue4/UnrealEngine/LocalBuilds/Engine/Linux/Engine/Extras/ushell && chmod +x ./**/*.sh' && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
 # Copy the Installed Build into a clean image, discarding the source build
 FROM prerequisites as minimal
@@ -184,12 +201,24 @@ COPY --from=builder --chown=ue4:ue4 /home/ue4/UnrealEngine/LocalBuilds/Engine/Li
 COPY --from=builder --chown=ue4:ue4 /home/ue4/UnrealEngine/Components/DDC /home/ue4/UnrealEngine
 COPY --from=builder --chown=ue4:ue4 /home/ue4/UnrealEngine/Components/DebugSymbols /home/ue4/UnrealEngine
 COPY --from=builder --chown=ue4:ue4 /home/ue4/UnrealEngine/Components/TemplatesAndSamples /home/ue4/UnrealEngine
+
+# Copy Install.ini from the builder image, so it can be used by tools that read the list of engine installations (e.g. ushell)
+COPY --from=builder --chown=ue4:ue4 /home/ue4/.config/Epic/UnrealEngine/Install.ini /home/ue4/.config/Epic/UnrealEngine/Install.ini
 WORKDIR /home/ue4/UnrealEngine
+
+# Add ushell to the system PATH and alias `ushell` to `ushell.sh`
+ENV PATH="$PATH:/home/ue4/UnrealEngine/Engine/Extras/ushell"
+RUN echo 'alias ushell="ushell.sh"' >> /home/ue4/.bashrc && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
+
+# Perform first-run setup for ushell
+RUN bash -c 'set -e; source /home/ue4/UnrealEngine/Engine/Extras/ushell/ushell.sh && exit 0' && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
 # Perform first-run setup for Mono, UnrealBuildTool and AutomationTool, which makes it possible to build Unreal projects and plugins as users other than `ue4`
 # (Note that this will only work with 4.26.0 and newer, older Engine versions will always require write access to `/home/ue4/UnrealEngine`)
 # See the comments on this issue for details, including the need to ensure $HOME is set correctly: <https://github.com/adamrehn/ue4-docker/issues/141>
-RUN ./Engine/Build/BatchFiles/Linux/Build.sh UnrealHeaderTool Linux Development -SkipBuild && \
+COPY print-editor-target.py /tmp/print-editor-target.py
+RUN EDITOR_TARGET=$(python3 /tmp/print-editor-target.py /home/ue4/UnrealEngine) && \
+	./Engine/Build/BatchFiles/Linux/Build.sh "$EDITOR_TARGET" Linux Development -SkipBuild && \
 	mkdir -p ./Engine/Programs/AutomationTool/Saved && \
 	chmod a+rw ./Engine/Programs/AutomationTool/Saved && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 
